import path from 'node:path';
import fs from 'fs-extra';
import { logger } from '../shared/logger.js';
import { colors } from '../cli/ui/colors.js';
import { toKebabCase } from '../shared/utils.js';

export async function addPluginCommand(
  pluginName: string,
  options: Record<string, unknown>
): Promise<void> {
  const category = (options.category as string) || 'frontend-extras';
  const pluginId = toKebabCase(pluginName);
  const pluginDir = getPluginDir(category, pluginId);

  if (await fs.pathExists(pluginDir)) {
    logger.error(
      `${colors.error('Plugin directory already exists:')} ${colors.path(pluginDir)}`
    );
    process.exit(1);
  }

  // Create plugin directory structure
  await fs.ensureDir(path.join(pluginDir, 'templates'));

  // Generate meta.ts
  const metaContent = generateMetaTemplate(pluginId, pluginName, category);
  await fs.writeFile(path.join(pluginDir, 'meta.ts'), metaContent);

  // Generate file-map.ts
  const fileMapContent = generateFileMapTemplate(pluginId);
  await fs.writeFile(path.join(pluginDir, 'file-map.ts'), fileMapContent);

  // Generate sample template
  const templateContent = `// Generated by {{projectName}}\n// Plugin: ${pluginName}\n\nexport {};\n`;
  await fs.writeFile(
    path.join(pluginDir, 'templates', 'sample.ts.hbs'),
    templateContent
  );

  logger.info(
    colors.success(`\nPlugin scaffolded at ${colors.path(pluginDir)}`)
  );
  logger.info(colors.subheading('Next steps:'));
  logger.info(
    `  ${colors.bullet('1.')} Edit ${colors.path(path.join(pluginDir, 'meta.ts'))} ${colors.muted('— deps, env vars, …')}`
  );
  logger.info(
    `  ${colors.bullet('2.')} Edit ${colors.path(path.join(pluginDir, 'file-map.ts'))} ${colors.muted('— output files')}`
  );
  logger.info(
    `  ${colors.bullet('3.')} Add templates in ${colors.path(path.join(pluginDir, 'templates'))}`
  );
  logger.info(
    `  ${colors.bullet('4.')} Register in ${colors.command('PLUGIN_MANIFEST')} ${colors.muted('in src/plugins/registry.ts')}`
  );
}

function getPluginDir(category: string, pluginId: string): string {
  const categoryDirMap: Record<string, string> = {
    'frontend-web': 'frontends/web',
    'frontend-mobile': 'frontends/mobile',
    'backend': 'backends',
    'api-style': 'api-style',
    'database': 'databases',
    'orm': 'orms',
    'auth': 'auth',
    'styling-web': 'styling/web',
    'styling-mobile': 'styling/mobile',
    'state': 'state',
    'forms': 'forms',
    'ui-library': 'ui-library',
    'api-client': 'api-client',
    'mobile-navigation': 'mobile-navigation',
    'frontend-extras': 'frontend-extras',
    'backend-extras': 'backend-extras',
    'testing': 'testing',
    'logging': 'logging',
    'monitoring': 'monitoring',
    'devtools': 'devtools',
    'devops': 'devops',
    'deployment': 'deployment',
  };

  const baseDir = categoryDirMap[category] || category;
  return path.resolve(process.cwd(), 'src', 'plugins', baseDir, pluginId);
}

function generateMetaTemplate(id: string, label: string, category: string): string {
  return `import type { PluginMeta } from '../../../shared/types.js';

const meta: PluginMeta = {
  id: '${id}',
  label: '${label}',
  description: 'TODO: Add description',
  category: '${category}',
  platformSupport: 'all',
  deps: [
    // { name: 'package-name', version: '^1.0.0' },
  ],
  devDeps: [
    // { name: 'package-name', version: '^1.0.0' },
  ],
  envVars: [
    // { key: 'ENV_VAR', defaultValue: '', comment: 'Description', target: 'frontend' },
  ],
  scripts: [
    // { name: 'script-name', command: 'command', target: 'frontend', description: 'Description' },
  ],
  conflicts: [],
  requires: [],
  showWhen: (draft) => {
    return true; // TODO: Add visibility conditions
  },
  order: 100,
};

export default meta;
`;
}

function generateFileMapTemplate(id: string): string {
  return `import type { PluginFileMap } from '../../../shared/types.js';

const fileMap: PluginFileMap = {
  files: [
    // {
    //   template: 'sample.ts.hbs',
    //   outputPath: 'lib/${id}.ts',
    //   target: 'frontend',
    //   when: (ctx) => true,
    // },
  ],
  injections: [
    // {
    //   template: 'import-injection.hbs',
    //   targetFile: 'src/server.ts',
    //   marker: '// PLUGIN_IMPORTS',
    //   target: 'backend',
    //   when: (ctx) => true,
    // },
  ],
};

export default fileMap;
`;
}