import type { Plugin, TemplateContext, Target } from '../shared/types.js';
import { TARGETS } from '../shared/constants.js';

interface EnvGroup {
  label: string;
  pluginId: string;
  vars: Array<{
    key: string;
    defaultValue: string;
    comment: string;
  }>;
}

export function buildEnvFile(
  plugins: Plugin[],
  target: Target,
  _context: TemplateContext
): string {
  const groups: EnvGroup[] = [];

  for (const plugin of plugins) {
    const varsForTarget = plugin.meta.envVars.filter((v) => v.target === target);

    if (varsForTarget.length === 0) continue;

    groups.push({
      label: plugin.meta.label,
      pluginId: plugin.meta.id,
      vars: varsForTarget.map((v) => ({
        key: v.key,
        defaultValue: v.defaultValue,
        comment: v.comment,
      })),
    });
  }

  if (groups.length === 0) return '';

  let content = `# Environment Variables\n`;
  content += `# Generated by create-fullstack-app\n`;
  content += `# Copy this file to .env and fill in your values\n\n`;

  for (const group of groups) {
    content += `# ─── ${group.label} ───────────────────────────────\n`;

    for (const v of group.vars) {
      if (v.comment) {
        content += `# ${v.comment}\n`;
      }
      content += `${v.key}=${v.defaultValue}\n`;
    }

    content += `\n`;
  }

  return content;
}

export function buildAllEnvFiles(
  plugins: Plugin[],
  context: TemplateContext,
  pathResolver: (relativePath: string, target: Target) => string
): Map<string, string> {
  const files = new Map<string, string>();

  const targets: Target[] = [TARGETS.FRONTEND, TARGETS.BACKEND, TARGETS.ROOT];

  for (const target of targets) {
    const content = buildEnvFile(plugins, target, context);

    if (!content) continue;

    if (target === TARGETS.FRONTEND && context.isSingleApp && context.isFullstack && context.hasBothPlatforms) {
      files.set('client/.env.example', content);
      files.set('mobile/.env.example', content);
    } else {
      const envPath = pathResolver('.env.example', target);
      files.set(envPath, content);
    }
  }

  return files;
}