import path from 'node:path';
import fs from 'fs-extra';
import type { GeneratorOptions, GeneratorResult, Target } from '../shared/types.js';
import { buildContext } from './context.js';
import { getLayout } from '../layouts/index.js';
import { FileWriter } from './file-writer.js';
import { InjectionProcessor } from './injection-processor.js';
import { renderTemplate } from './template-engine.js';
import { resolveDependencies } from './dependency-resolver.js';
import { buildScripts } from './script-builder.js';
import { buildAllEnvFiles } from './env-builder.js';
import { generatePackageJsonFiles } from './package-json-generator.js';
import { generateReadme } from './readme-generator.js';
import { generateGitignore } from './gitignore-generator.js';
import { validatePluginCompatibility } from './validators/plugin-compatibility.js';
import { detectFileCollisions } from './validators/file-collision.js';
import { runPostGenerate } from './post-generate.js';
import { logger } from '../shared/logger.js';
import { ValidationError } from '../shared/errors.js';

const TOTAL_STEPS = 16;

export async function runPipeline(options: GeneratorOptions): Promise<GeneratorResult> {
  const {
    projectName,
    outputDir,
    answers,
    activePlugins,
    dryRun = false,
    skipInstall = false,
    skipGit = false,
  } = options;

  const errors: string[] = [];
  const warnings: string[] = [];
  const result: GeneratorResult = {
    outputDir,
    filesWritten: [],
    packagesInstalled: false,
    gitInitialized: false,
    errors,
    warnings,
  };

  try {
    logStep(1, 'Building template context...');
    const context = buildContext(answers, activePlugins);

    logStep(2, 'Selecting layout strategy...');
    const layout = getLayout(context.structure);

    logStep(3, 'Setting up path resolver...');
    const resolvePath = (
      relativePath: string,
      target: Target | string,
      options?: { pluginCategory?: string; platformSupport?: 'all' | 'web-only' | 'mobile-only' | 'backend-only'; templatePath?: string }
    ): string => {
      return layout.resolvePath(relativePath, target as Target, context, options);
    };

    logStep(4, 'Validating plugin compatibility...');
    const compatibility = validatePluginCompatibility(activePlugins);
    if (!compatibility.valid) {
      throw new ValidationError('Plugin compatibility check failed', compatibility.errors);
    }
    warnings.push(...compatibility.warnings);

    logStep(5, 'Checking for file collisions...');
    const collisions = detectFileCollisions(activePlugins, context, resolvePath);
    if (collisions.hasCollisions) {
      for (const collision of collisions.collisions) {
        warnings.push(
          `File "${collision.path}" generated by multiple plugins: ${collision.plugins.join(', ')}`
        );
      }
    }

    logStep(6, 'Creating project directory...');
    if (!dryRun) {
      await fs.ensureDir(outputDir);
    }
    const writer = new FileWriter(outputDir, { dryRun });

    logStep(7, 'Scaffolding directory structure...');
    const dirs = layout.scaffold(projectName, context);
    for (const dir of dirs) {
      await writer.createDir(dir);
    }

    logStep(8, 'Writing layout configuration...');
    const layoutFiles = layout.rootConfig(context);
    for (const file of layoutFiles) {
      await writer.writeFile(file.path, file.content);
    }

    logStep(9, 'Generating files from plugins...');
    const injectionProcessor = new InjectionProcessor();

    for (const plugin of activePlugins) {
      for (const entry of plugin.fileMap.files) {
        if (entry.when && !entry.when(context)) {
          logger.debug(`Skipping ${entry.template} (condition not met)`);
          continue;
        }

        const templatePath = path.join(plugin.templateDir, entry.template);
        const content = renderTemplate(templatePath, context);
        const outputPath = resolvePath(entry.outputPath, entry.target, {
          pluginCategory: plugin.meta.category,
          platformSupport: plugin.meta.platformSupport,
          templatePath: entry.template,
        });

        await writer.writeFile(outputPath, content);
      }
    }

    logStep(10, 'Processing cross-plugin injections...');
    injectionProcessor.collectInjections(activePlugins, context, resolvePath);

    const injectionTargets = injectionProcessor.getAllTargetFiles();
    for (const targetFile of injectionTargets) {
      const existingContent = await writer.readFile(targetFile);
      if (existingContent) {
        const injectedContent = injectionProcessor.applyInjections(targetFile, existingContent);
        const cleanedContent = injectionProcessor.cleanMarkers(injectedContent);
        await writer.updateFile(targetFile, cleanedContent);
      } else {
        logger.warn(`Injection target file not found: ${targetFile}`);
      }
    }

    logStep(11, 'Building package.json files...');
    const pkgTargets = layout.packageJsonTargets(context);
    const dependencies = resolveDependencies(activePlugins, pkgTargets, context);
    const scripts = buildScripts(activePlugins, pkgTargets, context);
    const packageJsonFiles = generatePackageJsonFiles(pkgTargets, dependencies, scripts, context);

    for (const [filePath, content] of packageJsonFiles) {
      const existing = await writer.readFile(filePath);
      if (existing) {
        const merged = mergePackageJsons(existing, content);
        await writer.updateFile(filePath, merged);
      } else {
        await writer.writeFile(filePath, content);
      }
    }

    logStep(12, 'Building environment variable files...');
    const envFiles = buildAllEnvFiles(activePlugins, context, resolvePath);
    for (const [filePath, content] of envFiles) {
      await writer.writeFile(filePath, content);
    }

    logStep(13, 'Writing global configuration files...');

    await writer.writeFile('.gitignore', generateGitignore(context));

    await writer.writeFile('README.md', generateReadme(context, activePlugins));

    await writer.writeFile('.editorconfig', generateEditorConfig());

    if (!dryRun) {
      logStep(14, 'Running post-generation tasks...');
      const postResult = await runPostGenerate(outputDir, context, {
        skipInstall,
        skipGit,
      });
      result.packagesInstalled = postResult.installed;
      result.gitInitialized = postResult.gitInitialized;
    } else {
      logStep(14, 'Dry run — skipping post-generation');
    }

    result.filesWritten = writer.getFilesWritten();
    result.warnings = warnings;

    logger.success(`Project generated successfully! (${result.filesWritten.length} files)`);
  } catch (error) {
    if (error instanceof ValidationError) {
      result.errors = error.validationErrors;
    } else {
      result.errors = [(error as Error).message];
    }
    logger.error(`Generation failed: ${(error as Error).message}`);
  }

  return result;
}

function logStep(step: number, message: string): void {
  logger.step(step, TOTAL_STEPS, message);
}

function mergePackageJsons(existingJson: string, newJson: string): string {
  try {
    const existing = JSON.parse(existingJson);
    const incoming = JSON.parse(newJson);

    const merged = {
      ...existing,
      ...incoming,
      scripts: { ...(existing.scripts || {}), ...(incoming.scripts || {}) },
      dependencies: { ...(existing.dependencies || {}), ...(incoming.dependencies || {}) },
      devDependencies: { ...(existing.devDependencies || {}), ...(incoming.devDependencies || {}) },
    };

    if (existing.workspaces) {
      merged.workspaces = existing.workspaces;
    }

    return JSON.stringify(merged, null, 2) + '\n';
  } catch {
    return newJson;
  }
}

function generateEditorConfig(): string {
  return `root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[*.md]
trim_trailing_whitespace = false

[*.py]
indent_size = 4

[Makefile]
indent_style = tab
`;
}